### ISSUE TITLE
Clear previously received messages?

### ISSUE THREAD

**Issue by vk2mpj** [davidmckenzie/pagermon#111]
Is there a way to clear messages from the database? When setting up and testing, I used a busy channel here, and now it is working, I would like to clear the received messages and only display messages from the channel I am now monitoring.
Many thanks for the app.

**Comment by vk2mpj** [comment]
Many thanks for the rapid reply.
I am really at the limits of my experience and knowledge now. But I’ll have a scratch around and see what I can find
I’ve just gone through and set up a bunch of aliases… 
Worst case, if I can’t figure it out, the old messages will stay there

**Comment by DanrwAU** [comment]
Ok then, 
If you have other data in the database, best bet is to do the following.

- Login to the server you installed pagermon on.
- type `sqlite3` at the prompt. 
  you should receive a prompt like sqlite> 
- type `.open *path to pagermon*/server/messages.db` hit enter
- type `DELETE FROM messages; ` 
- Restart pagermon app to prevent any caching. 

Obviously make a backup before trying this `cp messages.db messages.backup`

**Comment by vk2mpj** [comment]
You sir, are a dead set legend. Thank you so much for your help.
I can handle / figure out most things when it comes to Linux, but I am a complete numpty when it comes to SQL.
That worked a treat. Again, thank you!!

**Comment by DanrwAU** [comment]
Glad to hear it 😄
