### ISSUE TITLE
Automate database upgrades

### ISSUE THREAD

**Issue by marshyonline** [davidmckenzie/pagermon#114]
I think moving forwards automated database upgrades should be come a thing.
This will streamline the process of upgrading servers and reduce the manual work required when new features are implemented.
@DanrwAU and @davidmckenzie - Thoughts?

**Comment by DanrwAU** [comment]
Agreed, Something i started trying to figure out back when i did the pushover per-alias stuff but couldn;t make any progress with my limited js and sql experience 😭

**Comment by davidmckenzie** [comment]
Solved in #113
