### ISSUE TITLE
Add documentation for Text Matching

### ISSUE THREAD

**Issue by pyrog** [davidmckenzie/pagermon#124]
Could you provide a screen copy of the settings page to show how text matching could be used ?

How to:
* Replace **RCR** by **Road Crash Rescue** ?
* Highlight **ALERT** or **FIRECALL** ?
* Use **regex** ?

Thank you 😀

**Comment by DanrwAU** [comment]
Hi @pyrog 

You can't do any replacing in the current implementation, only labeling on hover.
Highlighting of the word FIRECALL is in the default configuration, i highlight alert in my config as below.

![image](https://user-images.githubusercontent.com/26653344/48253847-73756e00-e45c-11e8-874e-8b930a5c1135.png)

Regex is a painful beast but very powerful once you know how to use it. 
I use regex for highlighting street directory addresses

See the below regex string and the text it matches. 

![image](https://user-images.githubusercontent.com/26653344/48253898-999b0e00-e45c-11e8-8d1c-c31b9addc22d.png)
![image](https://user-images.githubusercontent.com/26653344/48253946-b0416500-e45c-11e8-9210-c0ebb22d62c2.png)

Did this help at all?

**Comment by davidmckenzie** [comment]
Here's my text matching settings if it helps:

![matching](https://user-images.githubusercontent.com/1100348/48287347-b830f180-e4bc-11e8-90af-ffd97e53e301.jpg)

Not using any regex there, but can see highlight vs text replacing.

@s3m1s0n1c is working on some documentation - may be worth adding to the list of things that need words

**Comment by pyrog** [comment]
Thank you 😀
