### ISSUE TITLE
http fore Telegramm

### ISSUE THREAD

**Issue by 112bzo** [davidmckenzie/pagermon#125]
I see that i must place the API in te setting HTTP but i dont see that. How to use pagermon into a telegramm bot?

**Comment by davidmckenzie** [comment]
The Telegram API key should go in your settings page:

![tgram](https://user-images.githubusercontent.com/1100348/48287509-3a211a80-e4bd-11e8-85a0-df6e78ba3f7e.jpg)

**Comment by 112bzo** [comment]
Thanks but i only see pushover an not telegramm

Must i do somthimg in the script ?

**Comment by 112bzo** [comment]
oke, i run the 0.1.8.beta right now.... :-) 

[http://86.86.74.22:3000/](url)

**Comment by DanrwAU** [comment]
You can upgrade directly to 0.1.9. 

Should be able to just drop the new files over the old ones.  Obviously backup first thought please. 😄

**Comment by 112bzo** [comment]
It works, thanks all
