### ISSUE TITLE
Refactor delivery methods into plugin system

### ISSUE THREAD

**Issue by davidmckenzie** [davidmckenzie/pagermon#130]
Have some kind of extensible plugin system that allows users to pick and choose which notification methods they'd like to use. Need to consider DB structure - pop all the notification methods out into a JSON string?

Possibly use something like https://github.com/c9/architect

**Comment by davidmckenzie** [comment]
FYI @marshyonline @DanrwAU @s3m1s0n1c @all3kcis

I've started on this in the 'plugins' branch here: https://github.com/davidmckenzie/pagermon/tree/plugins

Still a lot to do but just as a heads up as the structure of the plugins is starting to take shape. The configuration definitions for each plugin will be stored in the plugins dir, but configuration itself will remain in the main config.json, just in a bit of a different format.

Global configuration for each plugin is pretty much done - the definitions have been copied into the relevant files and the config can be edited in UI no dramas. It's all ng-repeat so in theory infinitely scalable. Conversion of old config to new is also sorted, handled in the db upgrade thingo.

Hooks have been added into the message API route and is triggering the plugins all good, they just don't do anything yet. The plugins can be run either before or after message processing - I'm not sure of the use for the 'before' plugins, but I'm sure there's something neat that can be done there. I've tried to keep it forward-compatible as much as possible, so there's an 'event' variable that's just 'message' for everything at the moment, but thinking ahead we may want to add a plugin to extend something else, like the capcodeRefresh function or maybe something to intercept page views.

Next up for me will be converting the config on the alias level - I'll be doing this as a single text field on the capcodes table that stored a json variable. Only real way to keep it extensible, but should (hopefully) get the job done nicely. The DB upgrade scripts for this bit will be a little scary, as they'll need to do a recreate of the capcodes table - lots of places that can go wrong.

Once that's done it'll just be a matter of ripping out all of the code in the message API route into the individual modules, and a buttload of testing.

Now that I've typed it out it sounds like a lot more work than I thought it was 😁

**Comment by davidmckenzie** [comment]
Ok so this is kinda functionally done now. That was one of those all-day marathons where I forget to eat so it is almost certainly filled with bugs and stuff.

I've tested basically nothing of this so far, and documented nothing, but this could be considered ready for testing by the enormously brave.

**If you've got big enough balls to try this - please make sure you triple back up your messages.db file. It will probably blow up or something.**

That said... I would appreciate people who actually use these notification methods to test, as I'll just be mostly making sure the data *looks* right and sending a few dummy requests for services I can't quickly test.

I'm particularly concerned with any settings getting lost or aliases getting munged up, as they're the real dangerzones.

My todo list on this one for tomorrow (if I get time between work) is mostly cleanup and documentation, then the testing fun times.

**Comment by marshyonline** [comment]
Oh man I'm excited about this one
I'll pull this one down tonight and have a good ol play :D

**Comment by DanrwAU** [comment]
Ditto, I'll take a copy of my nasty Prod DB and spin up a test box .. great work

**Comment by s3m1s0n1c** [comment]
Nice one 👍

**Comment by DanrwAU** [comment]
OK i got mine running with my prod database. 
No errors in the migration from the surface, the global settings page migrated fine.

The capcode settings page doesn't seem to be displaying the correct state (Enabled/Disabled) after the migration, cycling seems to bring it back into sync. 
The setting IS correct in the database and the message is still pushed however the priority is also not being sent through correctly.

**Comment by DanrwAU** [comment]
Looks like the Priority wasn't migrated correctly, config before manually re-saving the priority
```
Pushover:
2|pagermon | 2018-11-18 08:17 +00:00:       { enable: true,
2|pagermon | 2018-11-18 08:17 +00:00:         priority: '1',
2|pagermon | 2018-11-18 08:17 +00:00:         group: 'urnmxjhdhmaf53keab2pe4x4g9sc3y',
2|pagermon | 2018-11-18 08:17 +00:00:         sound: '' },
```

Config after saving
```
 Pushover:
2|pagermon  | 2018-11-18 08:23 +00:00:       { enable: true,
2|pagermon  | 2018-11-18 08:23 +00:00:         priority: [Object],
2|pagermon  | 2018-11-18 08:23 +00:00:         group: 'mykey',
2|pagermon  | 2018-11-18 08:23 +00:00:         sound: '' },
```

**Comment by davidmckenzie** [comment]
Ah yep - the priority and sound will both be weird. Angular's ng-options directive takes a value and a label, but saves it as an object with both. Will look at either making it only save the value, or just migrating to the object on first load.

For required fields, we can just add a 'required' boolean to each config item and toggle it similar to the ng-disabled directives.

Odd that the enabled thing wasn't showing up right - when you say cycling it, was it after saving the config for that alias, or after restarting the app?

**Comment by DanrwAU** [comment]
I fixed it by saving the alias. ill try it again shortly.

**Comment by davidmckenzie** [comment]
Ok @DanrwAU just pushed a thing that *might* fix both of these things. It's some really nasty SQL but I think it works - I don't have much of a dataset to test with.

The boolean bits have been converted to:

```
        "enable": ' || REPLACE(REPLACE(COALESCE(push,0),0,'false'),1,'true') || ',
```

Basically saying, replace 0s with false and 1s with true - and if there's no data present, give it a 0 which is then replaced with a false...

Those option variables I've just dodgied to use the object format rather than messing with angular, should do the job but may or may not be missing the display value before saving, not sure how that's handled, will need to science it.
```
        "priority": {"value": "' || COALESCE(pushpri,'') || '"},
```

**Comment by davidmckenzie** [comment]
My limited testing says the value hackery does indeed work and is still pretty.

**Comment by DanrwAU** [comment]
Looks good 👍  just tested with my existing pushover aliases and they are all enabled and sending with the correct priority, 
Let me know if you want a copy of one of my DB's for testing if that makes it easier 😄

**Comment by davidmckenzie** [comment]
More todo:

* If there are no per-alias config settings, don't show the plugin in the alias config page
* Make the 'before' handler synchronous, and pass through a return object to allow proper manipulation of the message, and make 'before' plugins actually useful
* Hide plugin config options (instead of make read only) when the plugin isn't enabled
* Add a 'before' plugin for #134

**Comment by davidmckenzie** [comment]
Ok reworked this a bit to handle callbacks in the plugins - they can now manipulate the data in `before` plugins. Will add some bits to trigger common things like stopping processing of a message or to skip alias matching if you want to match alias manually somehow.

One important thing is that plugins now *must* call the callback when processing is finished.

**Comment by DanrwAU** [comment]
Looking good! 

I might look at doing https://github.com/davidmckenzie/pagermon/issues/109 as a before plugin if this is stable before i go back to work 😄

**Comment by davidmckenzie** [comment]
Done:

* If there are no per-alias config settings, don't show the plugin in the alias config page
* Make the 'before' handler synchronous, and pass through a return object to allow proper manipulation of the message, and make 'before' plugins actually useful. **Actually ended up making this async, but it's better this way.**
* Hide plugin config options (instead of make read only) when the plugin isn't enabled
* Add a 'before' plugin for #134 **This turned out pretty neat - @all3kcis you may want to test this**
* Add order to run plugins (?) - would be pretty important for the 'before' plugins to run in a consistent order if you're manipulating and sending back data. **Decided to scrap this since we're going async - all the before plugins will run simultaneously, and all the after plugins will run simultaneously. This hopefully won't cause any race conditions, but something to be mindful of in plugin development.**

Still todo:

* Cleanup all the noisy logging (and knock out #138 in the process if I'm lucky)

**Comment by DanrwAU** [comment]
Tested all the Plugins again, all still working well 👍

**Comment by marshyonline** [comment]
My apologies gents for not getting in on testing this one just yet, we have a bubba in hospital at the moment 

I hope to get some time tomorrow while I'm home to have a play. 
Looking over the changes, everything looks a++
You guys are doing a top job with this one

**Comment by takenalias** [comment]
I'm looking at giving this a test in the next few days. Does this have the filering enhancement, where by notifications can be selective sent say only be sent if the page contain certain text?

**Comment by DanrwAU** [comment]
No, i had a busy week and never got to do https://github.com/davidmckenzie/pagermon/issues/109 and between us i'm not sure i know how 🤣

**Comment by all3kcis** [comment]
I tested the plugins branch, the filter plugin works but for my use I need the opposite :)
I need to exclude message that do not match with pattern. 
I think we can duplicate filter plugin to "inverted filter"

I'll check friday for the "shell cmd" plugin.

**Comment by DanrwAU** [comment]
> I tested the plugins branch, the filter plugin works but for my use I need the opposite :)
> I need to exclude message that do not match with pattern.
> I think we can duplicate filter plugin to "inverted filter"

I just quickly added this to the filter plugin... try it out from this PR and see how you go.
https://github.com/davidmckenzie/pagermon/pull/142

**Comment by all3kcis** [comment]
I don't think so, I also need the aliases.
Moreover, it is still easier to use a single filter than to play with aliases.
I just looked at your code, I think it matches what I need.

**Comment by davidmckenzie** [comment]
Changes look good, though we probably could have just used inverse regex. See: https://stackoverflow.com/questions/406230/regular-expression-to-match-a-line-that-doesnt-contain-a-word

I haven't had much time for this stuff past couple of weeks, but will aim to have this branch merged over the weekend :)

**Comment by DanrwAU** [comment]
> I don't think so, I also need the aliases.
> Moreover, it is still easier to use a single filter than to play with aliases.
> I just looked at your code, I think it matches what I need.

This seems to do what you are asking for the alias side. 
![image](https://user-images.githubusercontent.com/26653344/49131436-42d27700-f32c-11e8-8e1b-e6157e8b4b39.png)

I guess it's up to @davidmckenzie if we leave the alias filters in that plugin

**Comment by davidmckenzie** [comment]
Ok guys pretty much good to merge, knocked off #138 too in a fit of productivity. I think I caught all the log statements but may have missed some. Even got separate files going in there for ya @marshyonline 

Will merge as soon as someone gives the final tick of approval :)

**Comment by DanrwAU** [comment]
I'm flat out all day today. I'll try and run through testing it tomorrow.
Good work!

**Comment by all3kcis** [comment]
See https://github.com/all3kcis/pagermon/commit/069d6dd5435057a0e02baad3f70dd36ac5d33fe2
Plugin shell command adaptation ;)
Step 1 : create alias and activate shell script
Step 2 : Create file script-<alias_id>.sh into plugins-script folder
Enjoy

**Comment by davidmckenzie** [comment]
Another thought @all3kcis - we should probably have the scripts as a subdirectory of the `plugins` directory. That way it's kinda forwards compatible, in that other plugins can include or reference data from within that structure. E.g. you might have `plugins/Shell/{alias-id}.sh` for the shell scripts, and `plugins/SMTP/${alias-id}.jpg` if you wanted to send an image with emails or something like that.

Would look a bit neater too, as you'd have:
```
plugins/Shell.js
plugins/Shell.json
plugins/Shell/101.sh
plugins/Shell/123.sh
```

etc...

**Comment by all3kcis** [comment]
Yes, good idea, I'll do it.

**Comment by marshyonline** [comment]
What a monster!
Top work by everyone :D
