### ISSUE TITLE
Sound missing

### ISSUE THREAD

**Issue by 112bzo** [davidmckenzie/pagermon#132]
I have pagermon working only how do I get the sound active?

**Comment by davidmckenzie** [comment]
What sound? Sorry not sure what you mean

**Comment by s3m1s0n1c** [comment]
Pagermon has no sound per say...

RTL_FM listens to the pager freq then pipes what it hears to Multimon which decodes it into text and then gets piped to pagermon app which processes the info..

Your not meant to hear that lovely POCSAG or Flex noise...

**Comment by 112bzo** [comment]
I see a bell into de GUI so i think i can use a sound notification when a new massage is arrived.. into the top i see refesh and than a Bell icon i can activite

**Comment by davidmckenzie** [comment]
That enables browser level notifications - I'm not sure whether you can configure the browser to make sound on one of those notifications, would be a browser or OS level configuration though.

**Comment by s3m1s0n1c** [comment]
Bet me to it @davidmckenzie 👍 

Mine Dings when a notification comes through but yeah prob browser/os setting somewhere..

**Comment by 112bzo** [comment]
Thanks, Iam happy that you make this software GUI..

+1
