### ISSUE TITLE
2 running PI's and one database

### ISSUE THREAD

**Issue by 112bzo** [davidmckenzie/pagermon#140]
Is it possible to link pagermon database in a UI. I have 2x raspberry pi running. One on Flex and one on Pocsag. But I want to use these notifications in an UI so merge them into a database.

Is that possible?

**Comment by davidmckenzie** [comment]
Yep, definitely :) Just set a different "identifier" in the client config for each site or system so you can differentiate between the two

**Comment by DanrwAU** [comment]
To further expand on what David has said, if you are running the server portion on both Pi's you will need to only do so on one and point both client config files to the single Pi,
The way i do this is to run a separate server version on a virtual private server.

There is no way currently to read from 2 database files.
