### ISSUE TITLE
Add Facebook Messager Group chat plugin

### ISSUE THREAD

**Issue by s3m1s0n1c** [davidmckenzie/pagermon#143]
Would be cool to intergrate with a group chat in fb messenger

Only cause everyone is playing with plugins atm :)

https://developers.facebook.com/docs/workplace/integrations/custom-integrations/bots/#botsingroups

**Comment by davidmckenzie** [comment]
https://github.com/Schmavery/facebook-chat-api

Looks simple enough, though having to login with username/pass is probably bad. There's an official API for it, but that's for page interactions, not really for something like this. May end up getting your account banned from it, not sure if they monitor for activity based on automation or user reports.

https://developers.facebook.com/docs/messenger-platform/send-messages/

> Subscription Messaging (beta)
Subscription messaging allows your Page to send recurring messages for specific use cases that are not subject to the 24-hour standard messaging window.

> A Page admin must apply for page-level permission to send subscription messages. If your Page has subscription messaging permission, users automatically opt-in to receive subscription messages when they start a conversation; however, it is highly recommended that your bot ask permission to send subscription messages to ensure a positive user experience.

So possible to do officially, but some hoops to jump through.

**Comment by DanrwAU** [comment]
Yeah i looked further into this one, i think it's a little out of my skill range especially since i don't use facebook and really don't wanna sign up for one 😛.

The official method seems to be for creating business based bots not sure how far down the rabbit hole i wanna go with that one.

**Comment by s3m1s0n1c** [comment]
No worries guys :) was worth a try..

I'm gonna close this request now as its in the "Too Hard Basket" & not practical with FB's API

Thanks 
Sonic
