### ISSUE TITLE
Duplicated column Aliase

### ISSUE THREAD

**Issue by pyrog** [davidmckenzie/pagermon#147]
<img width="710" alt="duplicated column aliases" src="https://user-images.githubusercontent.com/2158081/49280147-af16bd00-f489-11e8-857b-713dffbf95b8.png">

This happened for **non-logged in users** only.

**Comment by pyrog** [comment]
Seem to be:
https://github.com/davidmckenzie/pagermon/blob/5531fe09a8dda9ba640c1d592fe67cf7867ad826/server/views/index.ejs#L89

**Comment by davidmckenzie** [comment]
This is fixed in #139 already :)
