### ISSUE TITLE
Bug with new date sorting

### ISSUE THREAD

**Issue by DanrwAU** [davidmckenzie/pagermon#151]
Getting this on the new version for new messages via the websocket 😭 

![image](https://user-images.githubusercontent.com/26653344/49559610-6e281800-f963-11e8-8c95-4726f538bafa.png)

**Comment by davidmckenzie** [comment]
This is spooky... it's getting modified at some point in the plugin handler...

If I drop some console logs here:

```
                            console.log(row);
                            logger.main.debug('afterMessage start');
                            pluginHandler.handle('message', 'after', row, function(response) {
                              console.log(row);
                              logger.main.debug(util.format('%o',response));
                              logger.main.debug('afterMessage done');
```

It's clearly changing the timestamp to datetime format after plugins have run:

```
  timestamp: 1544070748,
[..]
  timestamp: '2018-12-06 15:12:15',
```

**Comment by davidmckenzie** [comment]
Ahahahahaha oh wow.

**Comment by davidmckenzie** [comment]
```
logger.main.debug(data);
```

```
    format: format.combine(
[..]
        format.timestamp({format:"YYYY-MM-DD HH:MM:SS"}),
```

...

I got no words.

PR incoming.

**Comment by marshyonline** [comment]
We should probably recreate the release too @davidmckenzie :)

**Comment by davidmckenzie** [comment]
Was thinking about that, then figured there's probably gonna be a couple more things sneak through that we didn't notice so will give it a couple of days :D
