### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by takenalias** [davidmckenzie/pagermon#155]
As new messages come in, they say invalid date, if the page is refreshed the date is then displayed.

![image](https://user-images.githubusercontent.com/11468979/49680546-8cb61c80-fae5-11e8-97a9-38c115758f9f.png)

 I'm on 2.0

**Comment by DanrwAU** [comment]
This was a bug in the original 0.2.0 release.

If your using git, just do another git pull and reload the website, it was fixed in https://github.com/davidmckenzie/pagermon/issues/151

As per the comments there, a re-release is waiting on any other uncaught bugs 😄

**Comment by DanrwAU** [comment]
👍
