### ISSUE TITLE
How to get a Telegram user id ?

### ISSUE THREAD

**Issue by pyrog** [davidmckenzie/pagermon#156]
Several ways to get a user id:

- From your Telegram app:
  - Start a new chat with **userinfobot**
  - Start the bot `/start`
  - The bot give a human readable answer with your Id, First and Last name.

  or

  - Start a new chat with **jsondumpbot**
  - Start the bot `/start`
  - The bot give a machine readable answer in **json** format. Your id is `from.id` or `chat.id`

- From your web browser ([source](https://github.com/s3m1s0n1c/pagermon/wiki/Notifications#telegram-channelgroupuser-chat-id)):
  - Open `https://api.telegram.org/botXXX:YYY/getUpdates`
  Where **XXX:YYY** is your bot API key like `517933208:Z1AcweYqmPgatZ4BARcwKxDCdOHByP13GOq`
   - The bot give a machine readable answer in **json** format. Your id is `from.id` or `chat.id`

**Comment by DanrwAU** [comment]
@s3m1s0n1c was working on documentation for this as part of https://github.com/davidmckenzie/pagermon/issues/122 i think.

**Comment by s3m1s0n1c** [comment]
This has been added to Wiki
https://github.com/pagermon/pagermon/wiki/Notifications#telegram-channelgroupuser-chat-id
