### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by pyrog** [davidmckenzie/pagermon#158]
http://127.0.0.1:3000/login redirect to the login page without any error messages.
(With or without a good Username and Password)

This issue happened only with the localhost address.
See [passport/issues#482](https://github.com/jaredhanson/passport/issues/482#issuecomment-377126345)

**Comment by marshyonline** [comment]
This may be an issue - I'm unable to login with no error being shown.
Expect i'm not logging into a local host - i'm hitting a host through Cloudflare

**Comment by davidmckenzie** [comment]
Looks like you're using ipv6 there - or is that the cloudflare IP? If cloudflare's, then could be a trust-proxy setting since it's not showing your real IP. Whatever it's showing there would be stored as the session (I think)

If it is your IP, then could be something borked with ipv6, will have to dig into that a bit more.

**Comment by marshyonline** [comment]
Yeah I'm using IPv6 - Cloudflare is forwarding the correct client IP's thankfully
This also happens when I bypass CF and hit the server direct over ipv4 and 6 :(

**Comment by marshyonline** [comment]
Over IPv4(From my mobile teathered to a laptop) https://pastebin.com/JfVT6v8z
Pastebin beacuse i hate code blocks on github issues and it breaking nice formatting

**Comment by marshyonline** [comment]
So far I have tried
- Clearing out the sessions DB
- Updating Passport to the latest version 

neither of these resolved the issue.

**Comment by davidmckenzie** [comment]
How odd! Will see if I can replicate. Is your hostname set in env variables?

**Comment by marshyonline** [comment]
removing the ENV and letting it sort itself has resolved it when access via hostname:3000
Still broken for it when accessing via the site URL tho :(

**Comment by marshyonline** [comment]
I'll add to this that the setup was working for quite a while and I had no issues then one night logins failed.
Adding debugging to the login stuff shows its authing ok
when hostname  ENV is set to the site URL - it still fails to login 

Looks like it may be failing to save cookie?

**Comment by DanrwAU** [comment]
I've been meaning to open an issue for something similar. 

I have 2 sites running 

root domain site.com
subdomain boringstuff.site.com 

Both have the same password set, i can login to the root domain, however logins to the subdomain fail unless the browser is in private mode, i suspect a cookie issue as well but haven't had a chance to look into it yet unfortunately.

**Comment by marshyonline** [comment]
https://github.com/davidmckenzie/pagermon/blob/30c1367f98ddfec636fb825a7d620d42329d9c01/server/app.js#L114

This is what is causing the issue - Commenting this out allows me to log in regardless of url used

**Comment by davidmckenzie** [comment]
Hmm that's what makes the cookie work across multiple domains (i.e. www and non-www). Wonder if a chrome update killed it.

**Comment by marshyonline** [comment]
At first I thought it was a browser issue but I tried across multiple devices and browsers with no luck :(

**Comment by timrowlands** [comment]
I am also having the same issue, however I am unable to log in to change the default user credentials.

**Comment by timrowlands** [comment]
Sorry to ping again, as per:

> [pagermon/server/app.js](https://github.com/davidmckenzie/pagermon/blob/30c1367f98ddfec636fb825a7d620d42329d9c01/server/app.js#L114)
> 
> Line 114 in [30c1367](/davidmckenzie/pagermon/commit/30c1367f98ddfec636fb825a7d620d42329d9c01)
> 
>  sessSet.cookie.domain = '.'+hostname; 
> This is what is causing the issue - Commenting this out allows me to log in regardless of url used

Fixes the issue with logging in locally. I am not running in a proxied environment yet.

**Comment by shutterfire** [comment]
Same error here - signing in at external devices does not work at all
Tried the actual ip adress, the hostname ("dietpi" in this case as well as "DietPi") and 0.0.0.0

Clicking on "Login" simply reloads the page without being logged in.

The fix mentioned here:

> [pagermon/server/app.js](https://github.com/davidmckenzie/pagermon/blob/30c1367f98ddfec636fb825a7d620d42329d9c01/server/app.js#L114)
> 
> Line 114 in [30c1367](/davidmckenzie/pagermon/commit/30c1367f98ddfec636fb825a7d620d42329d9c01)
> 
>  sessSet.cookie.domain = '.'+hostname; 
> This is what is causing the issue - Commenting this out allows me to log in regardless of url used

helped.

**Comment by davidmckenzie** [comment]
I've just submitted PR #188 that should hopefully fix this - this is one of those "welp, worked for me" problems, so not sure the dealio
