### ISSUE TITLE
POP out Filter box for non admin's

### ISSUE THREAD

**Issue by s3m1s0n1c** [davidmckenzie/pagermon#159]
Hey Guys,

Is the Pop-out filter box meant to be for Non-Admin Users or Admin's?

I think it looks very clunky if it is for Non-Admin users as well.. 

See Screeny below..

![image](https://user-images.githubusercontent.com/21308820/49776203-27656400-fd4f-11e8-9c0c-997696a20960.png)
![image](https://user-images.githubusercontent.com/21308820/49776465-3f89b300-fd50-11e8-8646-73c78937bc8e.png)

**Comment by davidmckenzie** [comment]
Yeah bit useless at the moment... the idea there is that we can add more stuff to it later on. Like if we ever tackle #52 it could be useful to have a 'filter out' and a 'show matching' button. Or could have an 'open in new tab' button that gives you a nice pretty view of a description of the alias or something and list of the messages beneath.

**Comment by s3m1s0n1c** [comment]
Is anyone really going use use Advanced Filtering?

I think keyword, Agency and Alias would safice..

Even so.. I dunno just seems clunky anyways even if advanced was there.. specially that 90% of users will prob be mobile users..

Just my 5 cents...

**Comment by s3m1s0n1c** [comment]
Fair comments..

Will close this one then as its not really an issue and has been explained.
