### ISSUE TITLE
Customize port number

### ISSUE THREAD

**Issue by 112bzo** [davidmckenzie/pagermon#162]
Is it possible to adjust the port 3000 in a different port? because I have 2x Rpi running. One with Flex and one with POCSAG but wants to put this POCSAG on port 3001.

First running @ : http://86.86.74.22:3000/

**Comment by 112bzo** [comment]
Where do i find that file? i have PM2 running.

**Comment by davidmckenzie** [comment]
Depends on your environment, but by default you'd place it in the server dir.

PM2 docos has more info on setting env variables: http://pm2.keymetrics.io/docs/usage/environment/

**Comment by 112bzo** [comment]
Sorry friends, can't find the file where i must chance the port setting. Like to have port 3001

**Comment by marshyonline** [comment]
If you haven't moved the file, it's in the same folder as app.js

**Comment by marshyonline** [comment]
You may also know it as this file if you didn't rename it
https://github.com/davidmckenzie/pagermon/blob/master/server/process-default.json

**Comment by 112bzo** [comment]
Case closed. I have made it. 

First Rpi [http://86.86.74.22:3000/](http://86.86.74.22:3000/) its the filter of my district
Second Rpi [http://86.86.74.22:3001](http://86.86.74.22:3001) its the Dutch network of pager alarms EMS

Thanks people.
