### ISSUE TITLE
Not all icons can be selected

### ISSUE THREAD

**Issue by shutterfire** [davidmckenzie/pagermon#178]
For some reason I can only use a very limited set of icons. Icons with a dash in their name seem to not work at all (heart-rate, briefcase-medical or something like that)

Here's what I tried:
500px works
amilia seems not to work
android works

So the dash thing does not seem to be the issue though

**Comment by 112bzo** [comment]
I have The same isseu

**Comment by davidmckenzie** [comment]
We're on an older version of FontAwesome (4.x), current icons can be seen here: https://fontawesome.com/v4.7.0/icons/

There were a few breaking changes in v5 so may not be simple to upgrade - could break existing aliases. Will need to test upgrading and see :)

**Comment by shutterfire** [comment]
Ah, okay. Proposal: Change the "all icons" link to make this clear

**Comment by marshyonline** [comment]
I've attempted the upgrade in the last week or two with the intent to has it go into master - its not a simple process :( 

I may re visit it in the future tho as i do like the look of the newer icons

**Comment by DanrwAU** [comment]
@marshyonline Agreed, i tried it a few months back and gave up as well lol

**Comment by davidmckenzie** [comment]
The changes for those curious: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

We might be able to get away with just using the v4 shims, but it reeks of "this could break without warning at some point" :(
