### ISSUE TITLE
client on startup

### ISSUE THREAD

**Issue by AllanRichardson** [davidmckenzie/pagermon#187]

**Comment by AllanRichardson** [comment]
is there any way to have the client start automagicly after boot?

**Comment by davidmckenzie** [comment]
Depends on your system ;) On linux you could add it to rc.local or something.

**Comment by marshyonline** [comment]
I do some crazy stuff with it as a system service, its not that hard to get setup :)

**Comment by DanrwAU** [comment]
I run it with PM2 on my Pi's it handles auto restarting ;-)

**Comment by AllanRichardson** [comment]
ok guys, thanks for your quick responses. im not very experienced with this stuff, but got pm2 to launch the server on start up. currently have 2 clients running. one of the clients is remote and one is local to the server. both running on raspberry pi

**Comment by AllanRichardson** [comment]
Got it!!! learned to use rc.local... thanks guys now to figure out how to mark issue closed

**Comment by AllanRichardson** [comment]
pm2 works better
