### ISSUE TITLE
Filtered Messages showing ALL new messages

### ISSUE THREAD

**Issue by jklnz** [davidmckenzie/pagermon#35]
When you click on a capcope on the main page to filter by that capcode - this works and displays only the messages to that capcode. But when a new message comes in from the decoder it gets shown at the top even though it does not match the filter.

**Comment by davidmckenzie** [comment]
Pushed a fix... I think it'll do it. Testing now :)

**Comment by davidmckenzie** [comment]
Ok tested, that should be working now! :)

Feel free to reopen if you have any trouble
