### ISSUE TITLE
Filtering messages scrolls to bottom

### ISSUE THREAD

**Issue by jklnz** [davidmckenzie/pagermon#37]
Just a minor issue, if you click on a capcode on the main page it takes you to the page where only the messages to that capcode is displayed. But it keeps the scroll position - so if you scrolled half way down the page then clicked on the capcode it will scroll halfway down the page when on the filtered messages view

**Comment by davidmckenzie** [comment]
Ah, that's that annoying angular routing thing. Hopefully easy fix :)

https://stackoverflow.com/questions/21055952/changing-route-doesnt-scroll-to-top-in-the-new-page
