### ISSUE TITLE
Duplicate messages ignored by time

### ISSUE THREAD

**Issue by jklnz** [davidmckenzie/pagermon#40]
Hey @davidmckenzie 
Just wondering if you could please add an option to ignore messages if it is within 20 (maybe have this user selectable?) seconds of the same message to the same address [as well as the current option to ignore if received in the last 10 messages].

**Comment by davidmckenzie** [comment]
I like that - user selectable time limit for the duplicate message filtering. Would be similar to how PDW works :)
