### ISSUE TITLE
Some capcodes not showing messages

### ISSUE THREAD

**Issue by jklnz** [davidmckenzie/pagermon#53]
A couple of capcodes are not showing the messages when you click on the capcode to view their messages:
![image](https://user-images.githubusercontent.com/26646690/27714351-72bde92a-5d84-11e7-95d1-33e243208465.png)

![image](https://user-images.githubusercontent.com/26646690/27714364-83bdd582-5d84-11e7-813a-6955664443f2.png)

**Comment by davidmckenzie** [comment]
Got it... pushing fix in a sec

**Comment by davidmckenzie** [comment]
Try now :) Typo in condition - `rowCount > 1` should be `rowCount > 0`

**Comment by jklnz** [comment]
Sweet, have just made the change on my end and it is working now thanks!
