### ISSUE TITLE
NVM issue

### ISSUE THREAD

**Issue by Shifteh-187** [davidmckenzie/pagermon#607]
whilst installing Server Portion

cd  pagermon/server
nvm install --loglevel verbose

`npm verbose stack     at async Arborist.reify (/root/.local/share/fnm/node-versions/v20.15.0/installation/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
npm error code EIO
npm error syscall read
npm error errno EIO
npm error Invalid response body while trying to fetch https://registry.npmjs.org/get-intrinsic: EIO: i/o error, read
npm verbose cwd /pagermon/server
npm verbose os Linux 6.1.0-21-amd64
npm verbose node v20.15.0
npm verbose npm  v10.8.1
npm verbose exit 1
npm verbose code 1
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-06-21T10_32_41_974Z-debug-0.log
root@Radio:/pagermon/server#
`

**Comment by eopo** [comment]
We don't offer support for nvm - I'd recommend heading over to https://github.com/nvm-sh/nvm
