### ISSUE TITLE
edit wiki to migrate from sqlite to mysql

### ISSUE THREAD

**Issue by erikklavora** [davidmckenzie/pagermon#615]
Well it is not actually a feature request but more if there is a how to to migrate from sqlite3 to mysql. does anyone have a how to that worked so we could add that to the wiki with a pull request ?
Thanks, Erik

**Comment by DanrwAU** [comment]
SQLIte has an export to CSV feature. MySQL has an import csv feature. Outside of that, you'll have to research how to make it happen. Google has some great tutorials for doing this.
