### ISSUE TITLE
PM2 Script fail "pm2 start process.json" 

### ISSUE THREAD

**Issue by bertonumber1** [davidmckenzie/pagermon#622]
**Describe the bug**

_pm2 fails to find app.js script_

**Steps to reproduce the behavior:**

_1. Go to ''cd ~/pagermon/server/"
2. type 'pm2 start process.json'_

**Expected behavior**
_pm2 to daemonize , cron to acknowledge and the script for server to run from app.js_

**Environment information:**
Rpi3b+ , Pagermon Pi  Image , RTL-SDR plugged in while going through steps.

 - Other details
 - 
 _- : Updated image , and tried image without updating. OOB _

**Additional context**
Not seen this before guys. i thought this would have worked out of the box but i cannot get it to work . What about ditching PM2 and maybe systemd service to handle pagermon?

**Actual Behaviour/Error:**

login as: pagermon
pagermon@192.168.0.14's password:
Linux raspberrypi 5.15.76-v7+ #1597 SMP Fri Nov 4 12:13:17 GMT 2022 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Nov 21 17:08:49 2024
pagermon@raspberrypi:~ $ cd ~/pagermon/server/
pagermon@raspberrypi:~/pagermon/server $ pm2 start process.json
[PM2] Spawning PM2 daemon with pm2_home=/home/pagermon/.pm2
[PM2] PM2 Successfully daemonized
[PM2] cron restart at 1 0 * * *
[PM2][WARN] Applications pagermon not running, starting...
[PM2][ERROR] Error: Script not found: /home/pi/pagermon/server/app.js
pagermon@raspberrypi:~/pagermon/server $ cd /home/pi/pagermon/server/
-bash: cd: /home/pi/pagermon/server/: No such file or directory
pagermon@raspberrypi:~/pagermon/server $ ls
app.js      Dockerfile.armhf  logs          package-lock.json     root
auth        hooks             messages.db   pids                  routes
config      knex              middleware    plugins               sessions
db.js       knexfile.js       node_modules  process-default.json  test
Dockerfile  log.js            package.json  process.json          themes
pagermon@raspberrypi:~/pagermon/server $ pagermon@raspberrypi:~ $ cd ~/pagermon/server/
pagermon@raspberrypi:~/pagermon/server $ pm2 start process.json
[PM2] Spawning PM2 daemon with pm2_home=/home/pagermon/.pm2
[PM2] PM2 Successfully daemonized
[PM2] cron restart at 1 0 * * *
[PM2][WARN] Applications pagermon not running, starting...
[PM2][ERROR] Error: Script not found: /home/pi/pagermon/server/app.js
pagermon@raspberrypi:~/pagermon/server $ cd /home/pi/pagermon/server/
-bash: cd: /home/pi/pagermon/server/: No such file or directory
pagermon@raspberrypi:~/pagermon/server $ ls
app.js      Dockerfile.armhf  logs          package-lock.json     root
auth        hooks             messages.db   pids                  routes
config      knex              middleware    plugins               sessions
db.js       knexfile.js       node_modules  process-default.json  test
Dockerfile  log.js            package.json  process.json          themes
pagermon@raspberrypi:~/pagermon/server $
 cd ~/pagermon/server/
 cd ~/pagermon/server/
pagermon@raspberrypi:~/pagermon/server $ pm2 start process.json
[PM2] Spawning PM2 daemon with pm2_home=/home/pagermon/.pm2
[PM2] PM2 Successfully daemonized
[PM2] cron restart at 1 0 * * *
[PM2][WARN] Applications pagermon not running, starting...
pagermon@raspberrypi:~/pagermon/server $on  process.json          themesns

Any help appreciated 

Thanks

**Comment by eopo** [comment]
You did not change the values in `process.json`, especially the path to app.js.
