### ISSUE TITLE
Pushover Priority Per Alias

### ISSUE THREAD

**Issue by thewillhargan** [davidmckenzie/pagermon#66]
Got the program up and running and it's great, but I'd really like to be able to push different aliases at different priorities.

For Example. I'd like to be able to push any messages that would usually go to my pager at Emergency Priority. Whereas other pages can be sent at normal priority

**Comment by davidmckenzie** [comment]
Would need DB structure change unfortunately - will have to keep this one on the backlog for when I eventually get around to redoing the DB side of things. Will be looking at backing it on MongoDB or DynamoDB :)

**Comment by marshyonline** [comment]
This is something i never thought of when i integrated pushover initially, but i really do like this idea. 
But David is right, its not something i would want to push out as it will require another database change and that's something I want to avoid doing again.
+1 on this idea, keen to see it in the newer versions

**Comment by marshyonline** [comment]
I have made this change in #74 :)
