### ISSUE TITLE
Regex Not matching

### ISSUE THREAD

**Issue by Lowestkillcount** [davidmckenzie/pagermon#78]
Hey Guys,

Having an issue getting regex to match with special characters with the text matching.

String i'm matching is ' G&S' using the following regex SHOULD work (?:\ G\&S) according the online testers i normally use, but it isn't working.. Even using a wildcard (?:\ G\.S) doesnt get it working. 
Any thoughts as to why or where for me to poke around? 

Thanks!

**Comment by davidmckenzie** [comment]
Just tested this, looks like it's because it's looking at the HTML entity (`&amp;`). Try matching on `G&amp;S` or `G.....S`. :)

**Comment by Lowestkillcount** [comment]
That got it going ....Thanks!
