### ISSUE TITLE
Aliases icons

### ISSUE THREAD

**Issue by framar1** [davidmckenzie/pagermon#81]
how do we add more or custom icons

**Comment by damiankw** [comment]
I don't believe you can. The icon system uses FontAwesome which, although are adding icons very frequently, you can't just add your own in. Have a look at the FontAwesome repository for more information: https://github.com/FortAwesome/Font-Awesome

**Comment by davidmckenzie** [comment]
Yah pretty much that ^ the only alternative would be to create your own custom font, but that'd be a whole lot of messy hackery :)

Something like this: https://glyphter.com/

You'd need to have SVGs of the icons you're looking to use.
