### ISSUE TITLE
Pushover causing application crash

### ISSUE THREAD

**Issue by DanrwAU** [davidmckenzie/pagermon#94]
Noticed this in my logs tonight - Seems to be causing the app to crash and restart, however the notification is sent. 

May be benign but not sure. 

```
2|pagermon |     at IncomingMessage.<anonymous> (/home/user/pagermon/server/node_modules/pushover-notifications/lib/pushover.js:167:12)
2|pagermon |     at emitNone (events.js:111:20)
2|pagermon |     at IncomingMessage.emit (events.js:208:7)
2|pagermon |     at endReadableNT (_stream_readable.js:1064:12)
2|pagermon |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2|pagermon |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2|pagermon | 2018-09-18 06:45 +00:00: (node:3588) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 echo listeners added. Use emitter.setMaxListeners() to increase limit
2|pagermon | Error: user identifier is not a valid user, group, or subscribed user key
2|pagermon |     at Pushover.errors (/home/user/pagermon/server/node_modules/pushover-notifications/lib/pushover.js:84:13)
2|pagermon |     at IncomingMessage.<anonymous> (/home/user/pagermon/server/node_modules/pushover-notifications/lib/pushover.js:167:12)
2|pagermon |     at emitNone (events.js:111:20)
2|pagermon |     at IncomingMessage.emit (events.js:208:7)
2|pagermon |     at endReadableNT (_stream_readable.js:1064:12)
2|pagermon |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2|pagermon |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
  
```

**Comment by marshyonline** [comment]
Things to check

- API Keys is OK

- USER/Group Key is ok

This error would tell me its getting a 400 response. 
Can add some debug code to print the response form PushOver

**Comment by marshyonline** [comment]
https://github.com/davidmckenzie/pagermon/blob/ee1c3c750925b0761608c82c79bcaeeedc39c874/server/routes/api.js#L784

Change this line to console.log(err);
Should give you an error and not boot you out

**Comment by DanrwAU** [comment]
I'll throw it in shortly and see if i can make it happen, i tried to do so later on last night and couldn't get it to happen again.

**Comment by marshyonline** [comment]
Ill drop it a PR tonight to stop it killing the app when it hits ann error

**Comment by davidmckenzie** [comment]
Was it happening after the change to push settings per alias, or only started more recently?

**Comment by DanrwAU** [comment]
Great question, i'm not sure. 

I'll pull some logs and take a looksie soon.

**Comment by marshyonline** [comment]
I don't recall ever seeing it in either version :(

**Comment by DanrwAU** [comment]
Looks like the issue did occur again today -
` 2|pagermon | 2018-09-19 02:01 +00:00: (node:91197) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 echo listeners added. Use emitter.setMaxListeners() to increase limit`

Thats the only entry in my node-app.stderr.log file. 
Doesn't correspond to a pushover notification this time.

**Comment by DanrwAU** [comment]
Just happened again simply from loading the page - Possibly the Sockets aren't being closed correctly after our api security changes?

**Comment by marshyonline** [comment]
This is looking like the case, I will debug shortly

**Comment by marshyonline** [comment]
Pull this branch and let me know how it goes?
I cant replicate the issue :(

https://github.com/marshyonline/pagermon/tree/EventFixes

**Comment by DanrwAU** [comment]
I can't seem to either now, without pulling your branch down. 

I'll do some testing and see if i can figure out how to reproduce then pull it down. 😭

**Comment by marshyonline** [comment]
see #95 re: sending errors to the error log and now killing the app on an error in pushover

**Comment by davidmckenzie** [comment]
Merged that in, lets see if we get any more descriptive errors now. Wonder if it was a transient issue on the pushover side

**Comment by DanrwAU** [comment]
I've pulled it onto the instance that was having the issue, i'll keep an eye out for errors. 

Didn't get a chance yesterday, was busy stealing free stuff from Vantage 😛

**Comment by DanrwAU** [comment]
Got another one! 

2|pagermon | 2018-09-21 02:13 +00:00: (node:65698) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 echo listeners added. Use emitter.setMaxListeners() to increase limit

Nothing in the logs surrounding it 

2018-09-21 01:44 +00:00: 1.2.3.4 - - [21/Sep/2018:01:44:15 +0000] "POST /api/messages HTTP/1.0" 200 5 "-" "-"
2018-09-21 01:46 +00:00: 1.2.3.4 - - [21/Sep/2018:01:46:43 +0000] "POST /api/messages HTTP/1.0" 200 5 "-" "-"
2018-09-21 01:47 +00:00: 1.2.3.4 - - [21/Sep/2018:01:47:37 +0000] "POST /api/messages HTTP/1.0" 200 5 "-" "-"
2018-09-21 01:52 +00:00: 1.2.3.4 - - [21/Sep/2018:01:52:27 +0000] "POST /api/messages HTTP/1.0" 200 5 "-" "-"
2018-09-21 01:57 +00:00: 1.2.3.4 - - [21/Sep/2018:01:57:10 +0000] "POST /api/messages HTTP/1.0" 200 5 "-" "-"
2018-09-21 02:14 +00:00: 1.2.3.4 - - [21/Sep/2018:02:14:26 +0000] "POST /api/messages HTTP/1.0" 200 5 "-" "-"
2018-09-21 02:34 +00:00: 1.2.3.4 - - [21/Sep/2018:02:34:01 +0000] "POST /api/messages HTTP/1.0" 200 5 "-" "-"

**Comment by marshyonline** [comment]
Can you check to make sure that user/group key is correct?

Can you also please add `io.sockets.setMaxListeners(20);` around line 103 of app.js?

I'm wondering if the new admin socket has put it on its limit

**Comment by DanrwAU** [comment]
Figured it out! 

I have an alias with 'Enable sending via Pushover' Enabled without a key! 

We should probably put some checks around that for stupid people like myself :P 

The Socket error seems to be independant of the pushover error - i just happened to get them at the same time the first time i saw it

**Comment by marshyonline** [comment]
Well, that's good to know :rofl: 
Checking should be easy to add - Just make it a required field on the client side.

As above, give that a crack and see if it spits the dummy again

**Comment by marshyonline** [comment]
Looks like its the actual pushover Libary causing it to throw the application out the window 
https://github.com/qbit/node-pushover/blob/4fa9d9a067acd2e2756428b9bd09901f9333a933/lib/pushover.js#L84

**Comment by DanrwAU** [comment]
I haven't seen the socket error since setting the max listeners to 20. I'd guess the Admin socket pushed it a little high 😄

**Comment by marshyonline** [comment]
Beautiful 💕 
Thats what I like to hear 

I shall push it tonight 😄

**Comment by DanrwAU** [comment]
I'll fix up the Commit for the pushover side tomorrow if i get time. I had a go at the GUI side but couldn't get the Javascript to work properly 😭

**Comment by marshyonline** [comment]
#96 is open :D

**Comment by DanrwAU** [comment]
https://github.com/davidmckenzie/pagermon/pull/97 Should stop pushover crashing the application when an User/Group key isn't set.

I'd like to do some validation in the GUI on these fields but Javascript isn't my strong suit 😞

**Comment by marshyonline** [comment]
This has been resolved :D
